source 'https://rubygems.org'

# Rubygems
gem "rake", '>= 0.9.4'

# Cocoapods
gem "motion-cocoapods", '~> 1.3.0'
gem "cocoapods" #, "= 0.20.2" # had to set this to 20.2 because of this https://github.com/HipByte/motion-cocoapods/issues/64

# RubyMotion
gem 'bubble-wrap', :require => ['bubble-wrap/core', 'bubble-wrap/http', 'bubble-wrap/reactor']
				   # :github => 'rubymotion/BubbleWrap'
				   # 'bubble-wrap/core', 'bubble-wrap/http', 'bubble-wrap/rss_parser', 
				   # 'bubble-wrap/reactor', 'bubble-wrap/ui', 'bubble-wrap/camera'
				   # 'bubble-wrap/location', 'bubble-wrap/media', 'bubble-wrap/all'

gem 'ProMotion' #, :github => 'clearsightstudio/ProMotion', :branch => 'version-1.0'
gem 'simple_si' # Wrapper for https://github.com/Sumi-Interactive/SIAlertView


# Development
gem 'awesome_print_motion' # aliased to ap